app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from .views import *

urlpatterns = [
    # path('items/api/<characters:int>', ItemsView.as_view()),
    path('', index, name="index"),
    path('search/', search_result_ajax, name="search"),
    path('item_search/', ajax_items_live_search, name="item_search"),
    path('transfer/', transfer_to_ajax, name="transfer"),
    path('delete_item/', delete_item_ajax, name="delete_item"),
    path('login/', LoginView.as_view(template_name='login_index.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name="logout"),
    path('register/', register, name="register"),
    path('upload/', upload, name="upload"),
    path('manage/', manage, name="manage"),
    path('create/', create_character, name="create_char"),

    path('', include('django.contrib.auth.urls')),

    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ddo_banker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    # path('bank/', include('app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Item, Character


class UploadFileForm(forms.Form):
    file = forms.FileField(allow_empty_file=False)
    character = forms.ChoiceField()

    def __init__(self, user):
        super(UploadFileForm, self).__init__()
        chars = Character.objects.filter(user=user)
        self.fields["character"].choices = ((ch.id, ch.name) for ch in chars)


class AddItemForm(forms.ModelForm):
    # file = forms.FileField(allow_empty_file=True, required=False)

    class Meta:
        model = Item
        fields = ["character",
                  # "name",
                  "mythic",
                  "reaper"]

    def __init__(self, user):
        super().__init__()
        character = forms.ModelChoiceField(queryset=Character.objects.filter(user=user), )
        # name = forms.ModelChoiceField(queryset=ItemList.objects.all())

        self.fields["character"].queryset = Character.objects.filter(user=user)

        self.fields["character"].widget.attrs.update({"class": "form-control dropdown", "data-live-search": "true"})
        # self.fields["name"].widget.attrs.update({"class": "form-control", "data-live-search": "true"})
        self.fields["mythic"].widget.attrs.update({"class": "form-control"})
        self.fields["reaper"].widget.attrs.update({"class": "form-control"})
        # self.fields["file"].widget.attrs.update({"class": "form-control"})

        # self.fields["name"].required = False
        self.fields["mythic"].required = False
        self.fields["reaper"].required = False
        self.fields["character"].required = True
        # self.fields["file"].required = False


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({"class": "form-control"})
        self.fields["email"].widget.attrs.update({"class": "form-control"})
        self.fields["password1"].widget.attrs.update({"class": "form-control"})
        self.fields["password2"].widget.attrs.update({"class": "form-control"})

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CreateCharacterForm(forms.Form):
    char_name = forms.CharField(max_length=32)


class DeleteCharacterForm(forms.ModelForm):

    class Meta:
        model = Character
        fields = ["id", "name"]

    def __init__(self, user):
        super(DeleteCharacterForm, self).__init__()
        self.fields["name"] = forms.ModelChoiceField(queryset=Character.objects.filter(user=user))

app/templates/add_character.html
{% extends "base.html" %}
{% block head %}
    {% load static %}
{% endblock %}
{% block content %}
{#    {% if user.is_authenticated %}#}
{##}
{#        <div class="container" id="top-content-header">#}
{#            <div class="container"#}
{#                 style="margin-top: 0; padding-top: 0; margin-bottom: 10px; padding-bottom: 10px;#}
{#                    border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;#}
{#                    justify-content: center">#}
{#                <div class="row" style="">#}
{#                    <div class="col-lg-3 top-header"><a href="/manage">Manage Items</a></div>#}
{#                    <div class="col-lg-3 top-header"><a href="/create">Characters</a></div>#}
{#                    <div class="col-lg-3 top-header"><a href="/upload">Upload</a></div>#}
{#                    <div class="col-lg-3 top-header"><a href="/logout">Logout</a></div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}

    <div>
        <div class="container" style="display: flex; justify-content: center; align-items: center;">
            <div class="container">
                <h2>Add character</h2>
                <p class="text" style="background-color: #1bef1b">{{ success }}</p>
                <form method="post" name="add_char">
                    {% csrf_token %}
                    {{ add_form.as_table }}
                    <input type="submit" name="add_char">
                </form>

                <h2>Delete character</h2>
                <form method="post" name="del_char">
                    {% csrf_token %}
                    {{ del_form.as_table }}
                    <input type="submit" name="del_char">
                </form>

            </div>
        </div>

    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=devide-width, initial-scale=1">
    <meta>
    <title>DDO Bank</title>
    {% load static %}

    {#    <link rel="icon" href="../static/images/favicon.ico" type="image/x-icon">#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
    <link rel="stylesheet" type="text/css" href="{% static "/css/index.css" %}"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7971486231528635"
            crossorigin="anonymous"></script>

    <script src="{% static '/frontend/main.js' %}"></script>

    {#    <script src="src/MDB-Free_4.20.0/js/bootstrap.js"></script>#}
    {#    <script src="src/MDB-Free_4.20.0/js/jquery.js"></script>#}
    {#    <script src="src/MDB-Free_4.20.0/js/mdb.js"></script>#}
    {#    <script src="src/MDB-Free_4.20.0/js/popper.js"></script>#}
    {#    <link rel="stylesheet" type="text/css" href="src/MDB-Free_4.20.0/css/bootstrap.css">#}
    {#    <link rel="stylesheet" type="text/css" href="src/MDB-Free_4.20.0/css/mdb.css">#}
    {#    <link rel="stylesheet" type="text/css" href="src/MDB-Free_4.20.0/css/style.css">#}
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4520822905197335"
            crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>
<body style="background-color: darkgray">
{% block header %}
    {% if user.is_authenticated %}
        <div class="container" id="top-content-header">
            <div class="container"
                 style="margin-top: 0; padding-top: 0; margin-bottom: 10px; padding-bottom: 10px;
                    border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;
                    justify-content: center">
                <div class="row" style="">
                    <div class="col-lg-4 top-header"><a href="/manage">Manage Items</a></div>
                    <div class="col-lg-4 top-header"><a href="/create">Characters</a></div>
                    {#                    <div class="col-lg-4 top-header"><a href="/upload">Upload</a></div>#}
                    <div class="col-lg-4 top-header"><a href="/logout">Logout</a></div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block content %}
{% endblock %}
</body>
<footer style="position: fixed; padding: 10px 10px 0px 10px; bottom: 0; width: 100%; height: 40px;
               margin: 10px 25% 0 25%">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7971486231528635"
            crossorigin="anonymous"></script>
    <!-- ad_1 -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-7971486231528635"
         data-ad-slot="1097611634"
         data-ad-format="auto"
         data-full-width-responsive="true"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    <div>
        &copy; Obel IX from Orien Server
    </div>
</footer>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block head %}
    {% load static %}
{% endblock %}
{% block content %}
{% endblock %}

app/templates/login_index.html
{% extends "base.html" %}
{% block head %}
    {% load static %}
{% endblock %}

{% block content %}

    <div class="container">
    <span>
        <br>
        <br>
    </span>
        <h1 style="padding-right: 0%; padding-left: 25%">Welcome to DDO Online Banker</h1>
        <div class="row justify-content-md-center">
            <div class="col-sm-8">
                <img src="{% static '/images/Molgra.png' %} ">
            </div>

            <div class="col-lg-4 justify-content-center"
                 style="margin-top: 25%; margin-bottom: 50%">
                {% if form.errors %}
                    <p>Your username and password didn't match. Please try again.</p>
                {% endif %}
                {{ context }}
                {% if next %}
                    {% if user.is_authenticated %}
                        <p>Your account doesn't have access to this page. To proceed,
                            please login with an account that has access.</p>
                    {% else %}
                        <p>Please login to see this page.</p>
                    {% endif %}
                {% endif %}


                <div class="text box box-flex">
                    <p>This is project that I decided to make in order to manage my items better.</p>

                    <p>So far, it has only few functionalities, but I will make it more usefull and prettier by the
                        time.</p>
                    <p><b>What can be expected?</b></p>
                    <p>More filters to filter your items. <br>Items will have properties as in game to filter by</p>
                    <p><b>How does it work?</b></p>
                    <p>1. You need to create a character(s) in top menu. Shared bank is default.</p>
                    <p>2. You need to add items to that character</p>
                    <p>3. Manage it! Keep track of your items. App will - hopefully - be useful to you.</p>

                    <p><i>Please, keep in mind, that this app is still in development. Do you have suggestion how to
                        make it better? <a>Write it here!</a></i></p>

                    <p>So try it and <a href="/register/" style="font-size: 20px">REGISTER HERE!</a></p>

                </div>
                <form class="form-control" method="post">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <td>{{ form.username.label_tag }}</td>
                            <td>{{ form.username }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.password.label_tag }}</td>
                            <td>{{ form.password }}</td>
                        </tr>
                    </table>

                    <input type="submit" value="login">
                    <input type="hidden" name="next" value="{{ next }}">
                </form>

                {# Assumes you set up the password_reset view in your URLconf #}
                <p><a href="{% url 'password_reset' %}">Lost password?</a></p>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/logout.html
{% extends "base.html" %}
{% block head %}
    {% load static %}
{% endblock %}
{% block content %}
    <div class="container" style="margin: 25% 50% 25% 25%; box-shadow: black;">
        <p>Thanks for using this DDO-O Banker</p>
            <a href="/login">Login again?</a>
        </div>
    </div>
{% endblock %}

app/templates/manage.html
{% extends "base.html" %}
{% block head %}
    {% load static %}
{% endblock %}

{% block content %}
{#    {% if user.is_authenticated %}#}
{##}
{#        <div class="container" id="top-content-header">#}
{#            <div class="container"#}
{#                 style="margin-top: 0; padding-top: 0; margin-bottom: 10px; padding-bottom: 10px;#}
{#                    border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;#}
{#                    justify-content: center">#}
{#                <div class="row" style="">#}
{#                    <div class="col-lg-4 top-header"><a href="/manage">Manage Items</a></div>#}
{#                    <div class="col-lg-4 top-header"><a href="/create">Characters</a></div>#}
{#                    <div class="col-lg-4 top-header"><a href="/upload">Upload</a></div>#}
{#                    <div class="col-lg-4 top-header"><a href="/logout">Logout</a></div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}


    <div>
        <div class="container" style="display: flex; justify-content: center; align-items: center;">
            <h2>Add Item as you like</h2>
        </div>
        <form class="form-control" method="post"
              style="display: flex; justify-content: center; align-items: center; background-color: darkgray; margin-left: fill"
              autocomplete="off">
            {% csrf_token %}
            <div class="container" style="display: flex; justify-content: center; align-items: center;">
                <div class="row">
                    <div class="col-md-3 autocomplete">
                        Item name
                        {#                        <input aria-label="Search" type="search" id="item-list-search-input"#}
                        {#                               class="text fa-search form-control"#}
                        {#                               placeholder="Search for item">#}
                        <input id="item-list-search-input" type="text" name="item-name"
                               class="text form-control"
                               placeholder="Search for item">

                    </div>
                    {% for item in item_form %}
                        <div class="col-md-3">{{ item.label }}<br>{{ item }}</div>
                    {% endfor %}
                    <div class="col-lg-12">
                        <input type="submit" class="btn btn-primary"
                               style="display: flex; justify-content: center; align-items: center;">
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="container">
        <div class="w-100 text-center">
            <form id="search-form" autocomplete="off">
                {% csrf_token %}
                <input type="text" id="search-input" class="text fa-search form-control" placeholder="Search for item">
            </form>

            <table class="table table-bordered" id="results-table-body">
                <thead>
                <tr>
                    <td>Character</td>
                    <td>Item name</td>
                    <td>Mythic bonus</td>
                    <td>Reaper bonus</td>
                    <td>Transfer</td>
                    <td>Delete</td>
                </tr>
                </thead>
                <tbody id="result-table-body">
                <tr id="not-visible">
                    <td colspan="6" id="search-hint">Start typing into search box for results</td>
                </tr>
                </tbody>
            </table>

            <div id="results-box" class="results not-visible">

            </div>

        </div>

    </div>

    <script>
        const url = window.location.href
        const csrf = document.getElementsByName("csrfmiddlewaretoken")[0].value


        function character_item_search_success(res) {
            if (res.data.length == 0) {
                var rowCount = resultsTable.rows.length;
                for (var i = 1; i < rowCount; i++) {
                    resultsTable.deleteRow(1);
                }
            }

            var rowCount = resultsTable.rows.length;
            for (var i = 1; i < rowCount; i++) {
                resultsTable.deleteRow(1);
            }

            for (i = 0; res.data.length; i++) {
                if (resultsTable.classList.contains("not-visible")) {
                    resultsTable.classList.remove("not-visible")
                }


                var item = res.data[i];
                console.log(item.character)

                var row = resultsTable.insertRow(1 + i);
                var character = row.insertCell(0);
                var name = row.insertCell(1);
                var mythic = row.insertCell(2);
                var reaper = row.insertCell(3);
                var transfer = row.insertCell(4);
                var del_item_button = row.insertCell(5);
                character.innerHTML = item.character;
                name.innerHTML = item.name;
                mythic.innerHTML = item.mythic;
                reaper.innerHTML = item.reaper;

                {#globalizeItemIdxBeforeAjaxSend(item);#}
                transfer.appendChild(select_character.cloneNode(true));
                transfer.id = item.item_idx;

                transfer.addEventListener("change",
                    function (ev) {
                        var selected_char = ev.target.options[ev.target.selectedIndex].value
                        console.log(ev.currentTarget.id)
                        $.ajax({
                            type: "POST",
                            url: "/transfer/",
                            data: {
                                "csrfmiddlewaretoken": csrf,
                                "item_id": ev.currentTarget.id,
                                "character": selected_char
                            },
                            success: (res) => {
                                console.log(res)
                            },
                            error: (res) => {
                                console.log(res)
                            },
                        });
                    }, false)

                del_item_button.appendChild(del_button.cloneNode(true));
                del_item_button.id += item.item_idx;
                del_item_button.addEventListener("click",
                    function (ev) {
                        $.ajax({
                            type: "POST",
                            url: "/delete_item/",
                            data: {
                                "csrfmiddlewaretoken": csrf,
                                "item_id": ev.path[1].attributes.id.nodeValue,
                            },
                            success: (res) => {
                                console.log(res)
                            },
                            error: (res) => {
                                console.log(res)
                            },
                        });
                    }, false)
            }
        }

        function item_search_success(res) {
            console.log(res)
            $("#item-list-search-input").autocomplete({
                source: res.data
            });
        }

        const sendSearchData = (item, search_url, success_function) => {
            $.ajax({
                type: "POST",
                url: search_url,
                data: {
                    "csrfmiddlewaretoken": csrf,
                    "item_name": item,
                },
                success: (res) => {
                    success_function(res);
                },
                error: (err) => {
                    console.log(err)
                }
            })
        }

        const searchForm = document.getElementById("search-form")
        const searchInput = document.getElementById("search-input")
        var resultsTable = document.getElementById("results-table-body")
        var del_button = document.createElement("input")
        del_button.setAttribute("type", "submit")
        del_button.setAttribute("value", "X")

        var select_character = document.querySelector("select#id_character.form-control");
        searchInput.addEventListener("keyup", e => {
            console.log(e.target.value)
            if (e.target.value == 1) {
                return;
            }

            if (resultsTable.classList.contains("not-visible")) {
                resultsTable.classList.remove("not-visible")
            }

            sendSearchData(e.target.value, "/search/", character_item_search_success)
        });

        const itemSearchInput = document.getElementById("item-list-search-input")
        itemSearchInput.addEventListener("keyup", e => {
            console.log(e.target.value)
            if (e.target.value == 1) {
                return;
            }

            if (resultsTable.classList.contains("not-visible")) {
                resultsTable.classList.remove("not-visible")
            }

            sendSearchData(e.target.value, "/item_search/", item_search_success)
        });

    </script>

{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head %}
    {% load static %}
{% endblock %}
{% block content %}
    <div class="container py-5">
	<h1>Register</h1>
        {% if messages %}
            <p class="text" style="background-color: #ff7a7a">
            {% for msg in messages %}
                {{ msg }}
            {% endfor %}
            </p>
        {% endif %}
	<form method="POST">
		{% csrf_token %}
		{{ register_form | crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}
{% block head %}
    {% load static %}
{% endblock %}
{% block content %}
{#    {% if user.is_authenticated %}#}
{##}
{#        <div class="container" id="top-content-header">#}
{#            <div class="container"#}
{#                 style="margin-top: 0; padding-top: 0; margin-bottom: 10px; padding-bottom: 10px;#}
{#                    border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;#}
{#                    justify-content: center">#}
{#                <div class="row" style="">#}
{#                    <div class="col-lg-3 top-header"><a href="/manage">Manage Items</a></div>#}
{#                    <div class="col-lg-3 top-header"><a href="/create">Characters</a></div>#}
{#                    <div class="col-lg-3 top-header"><a href="/upload">Upload</a></div>#}
{#                    <div class="col-lg-3 top-header"><a href="/logout">Logout</a></div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}

    <div class="container" style="margin-top: 10%; margin-bottom: -10%">
        I would like to recommend you using OCR, upload bunch of screenshots of items in .zip/.7zip file.
        After successfull upload, application will recognize the items from OCR and saves it to database under your acc.
        It saves Name of item, Mythic AND Reaper boost. It can be then displayed in "Manage Items" tab
    </div>

    <div class="container" style="margin-top: 25%; margin-bottom: 50%">
        Upload .zip/.7zip files with your images in it.
        Max file size: 200 MB

        <div>
            {% if errors %}
                {{ errors }}
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
{#                <label for="formFileLg" class="form-label"></label>#}
{#                <input id="upload-file" name="zipfile" class="form-control form-control-lg"#}
{#                       type="file"#}
{#                       accept=".zip,.7zip">#}
{#                <input type="submit">#}
                {{ form }}
                <input type="submit">
            </form>
        </div>
    </div>
    <script>
        var uploadField = document.getElementById("upload-file");

        uploadField.onchange = function () {
            if (this.files[0].size > 208576000) {
                alert("File is too big!");
                this.value = "";
            }
            ;
        };</script>

{% endblock %}